spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db_spin_demo?useUnicode=true&characterEncoding=utf-8&serverTimezone = GMT&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
#    prefix: classpath:/templates/
#    suffix: html
#    encoding: UTF-8
#    content-type: text/html
#    mode: HTML5


#mybatis:
#  mapper-locations: classpath:mapping/*.xml
#  type-aliases-package: cn.ndky.pojo
#  configuration:
#    map-underscore-to-camel-case: true
#    auto-mapping-behavior: full

mybatis-plus:
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true   #关闭 驼峰命名 下划线 映射
  #  这种是在  src 下创建mapping文件夹
  #    mapping-locations: classpath:cn/cyp/springsecurity/mapper/*.xml
  #  这个是在resources下创建mapping文件夹
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.ndky.pojo.**

shiro:
  login-url: /welcome
  unauthorized-url: /unauthorized
  anon-urls:
    - /login
    - /layuimini/**
    - /baiduyz/**
    - /my/**
server:
  servlet:
    context-path: /spindemo

